export const midhome = [{
        id: 1,
        imgprofile: "./Homemidimg/Ellipse 6 (1).svg",
        title: "Designsta",
        email: "@inner",
        lefttime: "25 m",
        messeg: "Twitterdagi ayol-erkak qarama-qarshiliginglardan o'zinglar zerikmadinglarmi?",
        imgtext: null,
        img: null,
        imgpunct: "./Homemidimg/Vector (3).svg",
        imgmessge: "./Homemidimg/comment.svg",
        imgrefresh: "./Homemidimg/retweet.svg",
        imglike: "./Homemidimg/like (1).svg",
        imgsend: "./Homemidimg/share.svg",
        imgstatsia: "./Homemidimg/statistics.svg",
        fuulllike: "50.4K Tweets",
        city: "Trending in Germany",
        revolution: "Revolution",
    },
    {
        id: 2,
        imgprofile: "./Homemidimg/Ellipse 6 (2).svg",
        title: "cloutexhibition",
        email: "@RajLahoti",
        lefttime: "22 m",
        messeg: "YPIP dasturining bu yilgi sezoni ham o’z nihoyasiga yetmoqda. Mentorlik davomida talaba va yangi bitiruvchilarni o’sayotganini ko’rib hursand bo’ladi odam.",
        imgtext: null,
        img: null,
        imgpunct: "./Homemidimg/Vector (3).svg",
        imgmessge: "./Homemidimg/comment.svg",
        imgrefresh: "./Homemidimg/retweet (1).svg",
        imglike: "./Homemidimg/like fill.svg",
        imgsend: "./Homemidimg/share.svg",
        imgstatsia: "./Homemidimg/statistics.svg",
        fuulllike: "50.4K Tweets",
        city: "Trending in Germany",
        revolution: "Revolution",
    }, {
        id: 3,
        imgprofile: "./Homemidimg/Ellipse 6 (3).svg",
        title: "CreativePhoto",
        email: "@cloutexhibition",
        lefttime: "1 h",
        messeg: "Обетда..... ",
        imgtext: "Кечиринглар",
        img: "./Homemidimg/image 8.svg",
        imgpunct: "./Homemidimg/Vector (3).svg",
        imgmessge: "./Homemidimg/comment.svg",
        imgrefresh: "./Homemidimg/retweet.svg",
        imglike: "./Homemidimg/like (1).svg",
        imgsend: "./Homemidimg/share.svg",
        imgstatsia: "./Homemidimg/statistics.svg",
        fuulllike: "50.4K Tweets",
        city: "Trending in Germany",
        revolution: "Revolution",
    },
]